repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
- repo: local
  hooks:
  - id: unittests
    name: unittests
    language: system
    entry: python -m unittest
    pass_filenames: false
    args: [
      'discover',
    ]
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    args: [
      'src',
      'tests',
    ]
- repo: https://github.com/PyCQA/pylint
  rev: v2.14.5
  hooks:
  - id: pylint
    pass_filenames: false
    args: [
      'src',
      'tests',
    ]
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    args: [
      'src',
      'tests',
    ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
- repo: https://github.com/terrencepreilly/darglint
  rev: v1.8.1
  hooks:
  - id: darglint
    args: [
      '-s',
      'google',
      'src',
      'tests',
    ]
