repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: no-commit-to-branch
    args: [--branch, master]
- repo: local
  hooks:
  - id: unittests
    name: unittests
    language: system
    entry: python -m unittest
    pass_filenames: false
    args: [
      'discover',
    ]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [
      'src',
      'tests',
      'docs',
    ]
- repo: https://github.com/PyCQA/pylint
  rev: v3.1.0
  hooks:
  - id: pylint
    pass_filenames: false
    args: [
      'src',
      'tests',
      'docs',
    ]
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    args: [
      'src',
      'tests',
      'docs',
    ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
- repo: https://github.com/terrencepreilly/darglint
  rev: v1.8.1
  hooks:
  - id: darglint
    args: [
      '-s',
      'google',
      'src',
      'tests',
      'docs',
    ]
