repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: no-commit-to-branch
    args: [--branch, master]

- repo: local
  hooks:
  - id: unittests
    name: unittests
    language: system
    entry: python -m unittest
    pass_filenames: false
    args: [
      'discover',
    ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/PyCQA/pylint
  rev: v3.2.3
  hooks:
    - id: pylint
      pass_filenames: false
      args: [
        'src',
        'tests',
        'docs',
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
